# Generated by Django 4.2.3 on 2024-03-06 23:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("chat_gp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="forum",
            managers=[
                ("forums", django.db.models.manager.Manager()),
            ],
        ),
    ]
