# Generated by Django 4.2.3 on 2024-03-08 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("chat_gp", "0002_alter_forum_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            managers=[
                ("categories", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="message",
            managers=[
                ("messages", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="forum",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat_gp.category"
            ),
        ),
    ]
