# Generated by Django 4.2.3 on 2024-03-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_gp", "0003_category_alter_message_managers_alter_forum_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.CharField(default="buss", max_length=500),
            preserve_default=False,
        ),
    ]
