# Generated by Django 5.0.3 on 2024-03-09 13:15

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_gp", "0006_post"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post",
            managers=[
                ("posts", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="No title", max_length=500),
        ),
    ]
